### PR TITLE
Add Twilio Support

### LINKED ISSUE #3: Add twilio support to notification service

### PR DESCRIPTION
**Pull request by dtoki**
Closes #3 & #15 

Builds on @songsc work  https://github.com/commitdev/zero-notification-service/pull/15; addresses @bmonkman  comments.

### CODE REVIEW

**Comment by dtoki** [comment]
Would this also close https://github.com/commitdev/zero/issues/244?

or is the backend example still needed? I could go ahead and do that.

**Comment by bmonkman** [comment]
Yeah I think it can close 244 as well.

**Comment by bmonkman** [comment]
Looks good, thanks! Can you please also bump the version in `Chart.yaml` so we can use the new helm chart values? You can also bump up the app version in that file to represent the new version of the app that will be released.

**Comment by dtoki** [comment]
Closes commitdev/zero#244

**Review by bmonkman — APPROVED** [review]

**Review by bmonkman — APPROVED** [review]

**Pull request merged**
